FORMAT: 1A

# MSON Minimal example

## Notes [/notes]
 
### List all [GET]
+ Response 200 (application/json)
    + Attributes (array[Note])
 
## Note [/notes/{id}]
+ Attributes
    + id: 42 (number) - id of the note
    + title: Buy Milk (string) - title of the note
    + timestamp: 2011-12-12 21:21:21 (timestamp) - last modified
  
### Retrieve a Note [GET]
+ Response 200 (application/json)
    + Attributes (Note)
